name: main.js CI

on:
  push:
    branches: [ live ]
  pull_request:
    branches: [ live ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use main.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
         npm i
         npm run build
         serve -s build
         sudo service nginx restart